### ISSUE TITLE
v1.0.2 not compatible with ESP8266 3.1.*

### ISSUE THREAD

**Issue by lathoub** [4dsystems/GFX4DIoD9#2]
Hi,

I have noticed that the latest version of this library does not work with the 3.1.* version of the ESP8266 (but working fine with ESP8266 V3.0.2).
When you compile the v1.0.2 version on v3.1.1 you get this error:

```
/Users/**/Documents/Arduino/libraries/GFX4DIoD9/src/GFX4dIoD9.cpp: In member function 'void GFX4dIoD9::begin()':
/Users/**/Documents/Arduino/libraries/GFX4DIoD9/src/GFX4dIoD9.cpp:309:21: error: cannot convert 'SPISettings' to 'uint32_t' {aka 'unsigned int'}
  309 |   if (SD.begin(_sd, spiSettings))
      |                     ^~~~~~~~~~~
      |                     |
      |                     SPISettings
```

The issue came with this modif on the ESP8266 side: https://github.com/esp8266/Arduino/commit/c487ca5233721ac49ca0dcfe103c73df9a4301ad as part of the move to SdFat 2.0.2

Albeit advertised as non-breaking in https://github.com/esp8266/Arduino/releases/tag/3.1.0

A simple `cast` to uint32_t did not work.

---

Another issue is:
```
/Users/**/Documents/Arduino/libraries/GFX4DIoD9/src/GFX4dIoD9.cpp: In member function 'void GFX4dIoD9::ImageWifi(boolean, String, uint16_t, String, String)':
/Users/**/Documents/Arduino/libraries/GFX4DIoD9/src/GFX4dIoD9.cpp:1305:49: error: no matching function for call to 'HTTPClient::begin(String&, uint16_t&, String&, String&)'
 1305 |       if (!http.begin(Address, port, hfile, sha1)) return;
      |                                                 ^
```
---
Do these issue relate to the ESP8266 version check? 
`#if ARDUINO_ESP8266_GIT_VER > 0x2843a5ac
`

Thanks!

**Comment by lubolura** [comment]
I just started with IOD and I have same issue with :  
309 |   if (SD.begin(_sd, spiSettings))
      |                     ^~~~~~~~~~~
      |                     |
      |                     SPISettings

Is there plan to fix it ? It seems I have to stop my work with IOD until it is not fixed ... or is there any way how to get around the problem ?
